export const profile = {
  name: "小省",
  role: "AI 训练师",
  intro: "把训练数据、规则文档、模型评测和自动化工具变成可复用、可检查、可交付的工作系统。",
};

export const navNodes = [
  { id: "about", label: "我是谁", node: "Data" },
  { id: "insights", label: "能力模型", node: "Prompt" },
  { id: "marble", label: "工作台", node: "Workflow" },
  { id: "community", label: "项目星图", node: "Projects" },
  { id: "cases", label: "案例研究", node: "Quality" },
  { id: "api", label: "工具接口", node: "Tools" },
];

export const skills = [
  {
    id: "prompt",
    node: "Prompt",
    title: "规则与任务拆解",
    summary: "把模糊需求拆成字段、正反例、边界条件、操作流程和验收标准。",
    detail: "关注标注规则、提示词规范和复杂任务的一致执行。",
  },
  {
    id: "data",
    node: "Data",
    title: "训练数据处理",
    summary: "清洗并转换 JSONL、表格、文本、图片和对话样本。",
    detail: "重点关注字段关系、命名分类、可追溯性和人工复核效率。",
  },
  {
    id: "workflow",
    node: "Workflow",
    title: "模型评测与自动化",
    summary: "把输出评估和重复操作做成清晰流程，提高质检与交付效率。",
    detail: "用 Codex、脚本和浏览器工具连接输入、处理、检查、报告和输出。",
  },
];

export const projects = [
  {
    id: "portfolio-world",
    title: "个人 3D 世界首页",
    type: "3D Site",
    background: "近期我把个人网站从静态作品集升级为可探索的 3D 能力地图，并完成公开部署。",
    goal: "用世界模型叙事展示 AI 训练、规则、评测、工具项目与成长路径。",
    role: "梳理信息架构、迭代视觉方向、实现 3D 与 Canvas 降级、响应式交互、构建和部署流程。",
    challenge: "既要保持沉浸感，也要保证移动端、低性能模式和 GitHub Pages 环境中的稳定可访问。",
    solution: "以媒体首屏和 3D 节点承载氛围，以结构化分区和项目弹窗承载真实内容，并准备静态部署构建。",
    deliverable: "公开网站、3D 场景、项目弹窗、轻量模式、GitHub Pages 与 Sites 构建配置。",
    review: "这次工作让我把视觉实验、工程降级、内容组织和发布维护串成一次完整交付。",
    skills: ["信息架构", "3D 交互", "响应式实现", "部署"],
  },
  {
    id: "prompt-system",
    title: "标注规则与提示词规范",
    type: "Rules",
    background: "训练数据任务如果缺少清晰规则，同一问题会被不同执行者做出不同判断。",
    goal: "把任务要求写成可理解、可执行、可质检的规则文档。",
    role: "拆解字段定义、正反例、边界情况、操作步骤、异常处理和验收标准。",
    challenge: "规则既要覆盖复杂情况，也要避免冗长到难以执行。",
    solution: "从真实错误和分歧样本反推规则缺口，用示例和决策路径降低歧义。",
    deliverable: "标注指南、提示词规范、边界案例、质检清单和版本更新记录。",
    review: "规则撰写训练的是把隐性判断变成团队可复用标准的能力。",
    skills: ["规则文档", "Prompt", "边界分析", "验收标准"],
  },
  {
    id: "data-cleaning",
    title: "JSONL 数据转换与 Excel 交付",
    type: "Data",
    background: "训练数据常以 JSONL 保存，但人工复核和业务交付更适合结构清楚的表格。",
    goal: "把 JSONL 数据稳定转换为 Excel，同时保留字段关系与中文内容。",
    role: "检查数据结构、设计列映射、处理嵌套字段、生成并验证 Excel 文件。",
    challenge: "需要兼顾嵌套数据、缺失字段、编码和后续人工检查体验。",
    solution: "使用结构化解析和明确列映射完成转换，并对行数、字段和值进行抽样核验。",
    deliverable: "可复用转换脚本、Excel 交付文件和字段核查结果。",
    review: "格式转换的价值不只是换后缀，而是让数据更容易被检查、沟通和继续处理。",
    skills: ["JSONL", "Excel", "字段映射", "数据验证"],
  },
  {
    id: "quality-review",
    title: "模型输出与内容质量评测",
    type: "Evaluation",
    background: "模型回答流畅不等于准确、完整、可用，也不代表更符合用户偏好。",
    goal: "建立能够解释差异、定位问题并支持偏好判断的评测维度。",
    role: "从准确性、完整性、指令遵循、可读性、风险边界和偏好排序等维度检查输出。",
    challenge: "主观判断需要转成可复现标准，同时保留对上下文与用户目标的理解。",
    solution: "结合正反例、错误分类和成对比较记录判断依据，用失败样本持续修正规则。",
    deliverable: "评测维度表、问题标签、样本对照、偏好理由和质量复盘。",
    review: "评测工作的核心不是打分，而是解释模型为什么好、哪里不好、怎样改进。",
    skills: ["模型评测", "偏好排序", "错误分析", "规则优化"],
  },
  {
    id: "automation-flow",
    title: "批量图片命名与整理报告",
    type: "Workflow",
    background: "大量图片需要识别、规范命名并保留成功与跳过记录，纯手工处理效率低且容易出错。",
    goal: "建立可核查、可回退的批量图片整理流程。",
    role: "设计命名规则、置信度与跳过条件，执行批量处理并输出结果报告。",
    challenge: "自动命名必须避免误判覆盖，还要处理重名、低置信度和异常文件。",
    solution: "把识别、评分、目标命名、冲突检查和报告拆成独立步骤，对不确定项保守跳过。",
    deliverable: "批量命名脚本、成功报告、跳过报告和人工复核列表。",
    review: "好的自动化不是把判断隐藏掉，而是把判断依据和失败路径一起留下。",
    skills: ["批处理", "命名规则", "异常处理", "报告输出"],
  },
  {
    id: "image-extractor",
    title: "网页图片提取器",
    type: "Tool",
    background: "网页素材收集时，手动定位、保存、筛选和命名会消耗大量时间。",
    goal: "做一个能识别网页图片资源并支持后续整理的浏览器工具。",
    role: "梳理真实使用流程，完善资源提取、界面反馈、文件导出和异常处理。",
    challenge: "网页图片可能来自 img、CSS、懒加载或不同尺寸链接，来源并不统一。",
    solution: "用浏览器扩展集中识别资源，配合本地整理流程完成筛选、保存和命名。",
    deliverable: "可安装浏览器扩展、资源列表、导出流程、使用说明和语法检查。",
    review: "这个项目让我更具体地理解工具产品中的状态反馈、边界情况和操作成本。",
    skills: ["浏览器扩展", "JavaScript", "素材管理", "工具体验"],
  },
  {
    id: "learning-game",
    title: "英语连连看游戏",
    type: "Learn",
    background: "学习内容如果只停留在文本，很难保持互动和反馈。",
    goal: "把英语词汇练习变成一个可玩的网页小游戏。",
    role: "设计关卡、词组、交互反馈和页面布局。",
    challenge: "游戏要简单可用，同时不能让布局在不同屏幕上破碎。",
    solution: "用清晰卡片、状态反馈和响应式布局承载学习任务。",
    deliverable: "可运行学习小游戏、关卡数据、交互反馈。",
    review: "这个项目训练了我把内容转成体验的能力。",
    skills: ["学习产品", "交互设计", "前端实现"],
  },
  {
    id: "ai-music",
    title: "《新白娘子》AI 音乐创作",
    type: "Music AI",
    background: "我想创作一首关于西湖的歌曲，用《白娘子传奇》的故事背景承载相遇、等待、宿命与离别。",
    goal: "把古典传说转译成具有现代旋律感、氛围感和情绪张力的中文说唱作品。",
    role: "确定故事与情绪方向，拆解歌词叙事，设计 130 BPM 的音乐风格参数，并整理 Suno 可执行提示词。",
    challenge: "既要让故事具有辨识度，又要避免停留在剧情复述；音乐还要兼顾忧郁氛围、旋律性和 Trap 律动。",
    solution: "以西湖意象串联故事，用情绪化旋律说唱重写人物感受；在 R&B 和弦上叠加 Trap 鼓组、弹跳 808、清晰 Hi-hat 和氛围合成器。",
    deliverable: "原创歌曲《新白娘子》、音乐视频、歌词方向和 Suno 风格提示词。",
    review: "这次创作让我完成了从主题构思、文化转译、提示词设计到生成作品展示的完整链路。",
    skills: ["音乐创作", "Suno", "提示词设计", "叙事表达"],
  },
];

export const journey = [];
