export const profile = {
  name: "小省",
  role: "AI 训练师 / 未来 AI 产品经理",
  intro: "训练 AI，训练自己。把学习、项目和工具变成可导航的个人世界模型。",
};

export const navNodes = [
  { id: "about", label: "我是谁", node: "Data" },
  { id: "insights", label: "能力模型", node: "Prompt" },
  { id: "marble", label: "工作台", node: "Workflow" },
  { id: "community", label: "项目星图", node: "Projects" },
  { id: "cases", label: "案例研究", node: "Quality" },
  { id: "api", label: "工具接口", node: "Tools" },
];

export const skills = [
  {
    id: "prompt",
    node: "Prompt",
    title: "提示词设计",
    summary: "把模糊需求拆成角色、目标、格式、限制和质检标准。",
    detail: "关注提示词的可复用性、边界条件和输出评估。",
  },
  {
    id: "data",
    node: "Data",
    title: "数据整理",
    summary: "整理文本、表格、图片和对话样本，形成可检索的素材库。",
    detail: "重点关注命名、分类、规则文档和质检流程。",
  },
  {
    id: "workflow",
    node: "Workflow",
    title: "自动化工作流",
    summary: "把重复任务做成流程，提高学习、整理和交付效率。",
    detail: "用 Codex、脚本和网页工具连接输入、处理、检查和输出。",
  },
];

export const projects = [
  {
    id: "portfolio-world",
    title: "个人 3D 世界首页",
    type: "3D Site",
    background: "我希望个人网站不是普通作品集，而是一张能展示学习路径、项目经验和工具关系的 3D 能力地图。",
    goal: "用世界模型风格搭建一个沉浸式个人首页，展示“训练 AI，训练自己”的主线。",
    role: "梳理信息架构、设计视觉方向、实现响应式页面、建立右下角 3D 节点导航。",
    challenge: "需要同时有个人表达、科技感和真实可浏览的页面结构，不能只停留在视觉 mockup。",
    solution: "用媒体首屏承载世界模型氛围，用网格分区组织能力、项目、案例和工具接口。",
    deliverable: "可运行个人网站、3D 节点导航、项目弹窗、移动端适配。",
    review: "个人网站本身就是项目案例，能展示我如何把需求拆成结构并逐步落地。",
    skills: ["前端实现", "信息架构", "3D 交互"],
  },
  {
    id: "prompt-system",
    title: "提示词系统",
    type: "Prompt",
    background: "AI 输出质量经常取决于需求是否被拆清楚，而不是一句简单指令。",
    goal: "建立一套可以复用的提示词拆解方法。",
    role: "把任务拆成角色、目标、输入、输出格式、限制和质检标准。",
    challenge: "提示词既不能太泛，也不能复杂到难以复用。",
    solution: "用模板化结构记录每次测试结果，并根据失败样本反向优化提示词。",
    deliverable: "提示词模板、测试记录、输出质量检查清单。",
    review: "提示词设计训练的是需求理解能力，也是 AI 产品工作的底层能力。",
    skills: ["Prompt", "需求拆解", "输出评估"],
  },
  {
    id: "data-cleaning",
    title: "素材与数据整理",
    type: "Data",
    background: "学习和项目过程中会积累大量图片、文本、链接和表格，如果不整理就无法复用。",
    goal: "把碎片资料整理成可命名、可分类、可检索的素材库。",
    role: "制定命名规则、分类字段和整理流程。",
    challenge: "素材来源复杂，格式不统一，容易出现重复和丢失上下文。",
    solution: "用规则表和脚本辅助整理，把人工判断集中在分类和质量检查上。",
    deliverable: "素材库结构、命名规范、整理报告。",
    review: "数据整理不是杂活，它决定后续训练、检索和复盘能不能跑起来。",
    skills: ["数据整理", "规则设计", "质检"],
  },
  {
    id: "quality-review",
    title: "内容质检标准",
    type: "Quality",
    background: "AI 输出看起来完整，不代表真的准确、可用或符合用户目标。",
    goal: "建立可说明的内容质量检查标准。",
    role: "从准确性、完整性、可读性、目标匹配和风险边界几个维度检查输出。",
    challenge: "质量判断容易主观，需要转成可执行的检查项。",
    solution: "把优秀样本和低质量样本并列对比，沉淀判断依据。",
    deliverable: "质检表、样本对照、问题分类。",
    review: "质检能力会直接影响 AI 训练任务和产品体验判断。",
    skills: ["质量评估", "样本分析", "规则优化"],
  },
  {
    id: "automation-flow",
    title: "自动化工作流",
    type: "Workflow",
    background: "很多学习和交付任务都有重复步骤，适合用工具和脚本串起来。",
    goal: "减少手动重复操作，把时间放在判断和创作上。",
    role: "识别重复流程，拆解输入、处理、检查和输出节点。",
    challenge: "自动化不能只追求省事，还要保证结果可检查、可回退。",
    solution: "用小工具先解决局部问题，再逐步组合成稳定流程。",
    deliverable: "工作流说明、工具脚本、检查步骤。",
    review: "自动化是把个人经验变成系统能力的一种方式。",
    skills: ["Workflow", "脚本思维", "效率工具"],
  },
  {
    id: "image-extractor",
    title: "网页图片提取器",
    type: "Tool",
    background: "收集网页图片素材时，手动保存、筛选和命名很耗时。",
    goal: "做一个更高效的网页图片提取和整理工具。",
    role: "梳理使用场景、检查文件结构、处理命名和导出流程。",
    challenge: "图片来源不统一，需要兼顾可用性和后续整理。",
    solution: "通过浏览器扩展和本地文件整理流程，把素材获取变成可复用工具。",
    deliverable: "网页图片提取器、整理规则、使用记录。",
    review: "工具项目让我更理解真实使用中的细节摩擦。",
    skills: ["工具开发", "素材管理", "浏览器扩展"],
  },
  {
    id: "learning-game",
    title: "英语连连看游戏",
    type: "Learn",
    background: "学习内容如果只停留在文本，很难保持互动和反馈。",
    goal: "把英语词汇练习变成一个可玩的网页小游戏。",
    role: "设计关卡、词组、交互反馈和页面布局。",
    challenge: "游戏要简单可用，同时不能让布局在不同屏幕上破碎。",
    solution: "用清晰卡片、状态反馈和响应式布局承载学习任务。",
    deliverable: "可运行学习小游戏、关卡数据、交互反馈。",
    review: "这个项目训练了我把内容转成体验的能力。",
    skills: ["学习产品", "交互设计", "前端实现"],
  },
  {
    id: "ai-music",
    title: "音乐生成评估",
    type: "Music AI",
    background: "我的音乐学背景可以帮助我从结构、节奏、风格和听感角度评估生成音乐。",
    goal: "建立更细致的音乐生成质量评估维度。",
    role: "拆解旋律、节奏、风格一致性和情绪表达等指标。",
    challenge: "音乐评价既有专业标准，也有主观听感。",
    solution: "把听感拆成结构完整度、风格贴合度、重复度和情绪表达。",
    deliverable: "音乐评价维度表、样例分析、质量复盘。",
    review: "音乐背景让我在多模态 AI 评估上有自己的辨识度。",
    skills: ["音乐学", "质量评估", "多模态 AI"],
  },
  {
    id: "future-pm",
    title: "AI 产品经理路径",
    type: "Future",
    background: "我希望从 AI 训练师起步，逐步转向理解用户、数据和模型闭环的 AI 产品经理。",
    goal: "把训练任务、工具项目和个人网站沉淀成产品思维证据。",
    role: "持续记录学习、项目、复盘和工具方法。",
    challenge: "转型需要证明的不只是兴趣，而是可持续的学习和交付能力。",
    solution: "用项目串起能力，用复盘说明判断，用网站持续展示成长路径。",
    deliverable: "个人能力地图、项目案例、未来学习路线。",
    review: "训练 AI 的过程，也是在训练我自己的产品判断。",
    skills: ["产品意识", "AI 训练", "成长路径"],
  },
];

export const journey = [];
